###########################################
#### Do not edit this file ################
#### It has been auto-generated ###########
###########################################
from setuptools import setup, find_packages
import os
import sys

install_requires = ["numpy"]

setup(
    name="sstcam",
    version="0.1.0",
    description="The SSTCAM software python package.",
    packages=find_packages(),
    provides=["sstcam"],
    license="GNU Lesser General Public License v3 or later",
    install_requires=install_requires,
    # package_dir = {"sstcam": "python/sstcam"},
    package_data = {
        '': ['_ext/*']
      },
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
    ],
    # entry_points={
    #     "console_scripts": [
    #     ]
    # },
)