package:
  name: zeromq
  version: 4.3.2

source:
  fn: v4.3.2-win.tar.gz
  url: https://github.com/zeromq/libzmq/archive/v4.3.2-win.tar.gz

build:
  string: "0"

requirements:
    build:
      # - python
      # - setuptools
#       - pybind11


